version: '3.1'

services: # containers

  nest: # internal dns name
    build:
      context: .
      args:
        - NODE_ENV=development
    command: 'yarn start:dev'
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - .:/opt/node_app:delegated
      - /opt/node_app/node_modules
    environment:
      REDIS_HOST: redis
      APP_SECRET: ${APP_SECRET}
      MTB_PROJECT_KEY: ${MTB_PROJECT_KEY}
      GOOGLE_MAPS_KEY: ${GOOGLE_MAPS_KEY}
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:5
    logging:
      driver: none

  postgres:
    image: mdillon/postgis:11
    environment:
      POSTGRES_PASSWORD: development-password
      POSTGRES_DB: mtb-nest
    volumes:
      - postgres:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  notused:
  postgres:
